
apiVersion: apps/v1 #App API version

kind: Deployment #Docker resource kind we are creating (Deployment Object)

metadata:
  name: springboot-crud-app-deployment #Name of deployment

spec:
  selector:
    matchLabels:
      app: springboot-k8s-mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql
    spec:
      containers:
        - name: springboot-crud-k8s #Get my image from the docker and run inside the K8s pods
          image: springboot-crud-k8s:1.0
          ports:
            - containerPort: 8085
          env: #Setting env var
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: user
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root



---

apiVersion: v1 #K8s API version

kind: Service #K8s resource kind we are creating

metadata: #Metadata of the resource kind we are creating
  name: springboot-crud-svc

spec:
  selector:
    app: springboot-crud-mysql
  ports:
    - protocol: "TCP"
      port: 8085 #The port that the service is running on the cluster
      targetPort: 8085 #The port exposed by the service
  type: NodePort #Type of the service
